#ifndef DRUMMAP_H
#define DRUMMAP_H

// Roland GS Drumset

const char *const DrumMap[] = {	"0",
								"1",
								"2", 
								"3",
								"4",
								"5",
								"6",
								"7",
								"8",
								"9",
								"10",
								"11",
								"12",
								"13",
								"14",
								"15",
								"16",
								"17",
								"18",
								"19",
								"20",
								"21",
								"22",
								"23",
								"24",
								"25",
								"26",
								"High Q",
								"Slap",
								"Scratch Push",
								"Scratch Pull",
								"Sticks",
								"Square Click",
								"Metronome Click",
								"Metronome Bell",
								"Kick Drum 2",
								"Kick Drum 1",
								"Side Stick",
								"Snare Drum 1",
								"Hand Clap",
								"Snare Drum 2",
								"Low Tom 2",
								"Closed Hi-Hat",
								"Low Tom 1",
								"Pedal Hi-Hat",
								"Mid Tom 2",
								"Open Hi-Hat",
								"Mid Tom 1",
								"High Tom 2",
								"Crash Cymbal 1",
								"High Tom 1",
								"Ride Cymbal 1",
								"Chinese Cymbal", 
								"Ride Bell",
								"Tambourine",
								"Splash Cymbal",
								"Cowbell",
								"Crash Cymbal 2",
								"Vibra-slap",
								"Ride Cymbal 2",
								"High Bongo",
								"Low Bongo",
								"Mute High Conga",
								"Open High Conga",
								"Low Conga",
								"High Timbale",
								"Low Timbale",
								"High Agogo",
								"Low Agogo",
								"Cabasa",
								"Maracas",
								"Short Hi Whistle",
								"Long Low Whistle",
								"Short Guiro",
								"Long Guiro",
								"Claves",
								"High Wood Block",
								"Low Wood Block",
								"Mute Cuica",
								"Open Cuica",
								"Mute Triangle",
								"Open Triangle",
								"Shaker",
								"Jingle Bell",
								"Belltree",
								"Castanets",
								"Mute Surdo",
								"Open Surdo",
								"88",
								"89",
								"90",
								"91",
								"92", 
								"93",
								"94",
								"95",
								"96",
								"97",
								"98",
								"99",
								"100",
								"101",
								"102", 
								"103",
								"104",
								"105",
								"106",
								"107",
								"108",
								"109",
								"110",
								"111",
								"112", 
								"113",
								"114",
								"115",
								"116",
								"117",
								"118",
								"119",
								"120",
								"121",
								"122", 
								"123",
								"124",
								"125",
								"126",
								"127"};
								
const char *const NoteMap[] = {	"C0",
                                "C#0",
                                "D0",
                                "D#0",
                                "E0",
                                "F0",
                                "F#0",
                                "G0",
                                "G#0",
                                "A0",
                                "A#0",
                                "B0",
                                "C1",
                                "C#1",
                                "D1",
                                "D#1",
                                "E1",
                                "F1",
                                "F#1",
                                "G1",
                                "G#1",
                                "A1",
                                "A#1",
                                "B1",
                                "C2",
                                "C#2",
                                "D2",
                                "D#2",
                                "E2",
                                "F2",
                                "F#2",
                                "G2",
                                "G#2",
                                "A2",
                                "A#2",
                                "B2",
                                "C3",
                                "C#3",
                                "D3",
                                "D#3",
                                "E3",
                                "F3",
                                "F#3",
                                "G3",
                                "G#3",
                                "A3",
                                "A#3",
                                "B3",
                                "C4",
                                "C#4",
                                "D4",
                                "D#4",
                                "E4",
                                "F4",
                                "F#4",
                                "G4",
                                "G#4",
                                "A4",
                                "A#4",
                                "B4",
                                "C5",
                                "C#5",
                                "D5",
                                "D#5",
                                "E5",
                                "F5",
                                "F#5",
                                "G5",
                                "G#5",
                                "A5",
                                "A#5",
                                "B5",
                                "C6",
                                "C#6",
                                "D6",
                                "D#6",
                                "E6",
                                "F6",
                                "F#6",
                                "G6",
                                "G#6",
                                "A6",
                                "A#6",
                                "B6",
                                "C7",
                                "C#7",
                                "D7",
                                "D#7",
                                "E7",
                                "F7",
                                "F#7",
                                "G7",
                                "G#7",
                                "A7",
                                "A#7",
                                "B7",
                                "C8",
                                "C#8",
                                "D8",
                                "D#8",
                                "E8",
                                "F8",
                                "F#8",
                                "G8",
                                "G#8",
                                "A8",
                                "A#8",
                                "B8",
                                "C9",
                                "C#9",
                                "D9",
                                "D#9",
                                "E9",
                                "F9",
                                "F#9",
                                "G9",
                                "G#9",
                                "A9",
                                "A#9",
                                "B9",
                                "C10",
                                "C#10",
                                "D10",
                                "D#10",
                                "E10",
                                "F10",
                                "F#10",
                                "G10",}; 							


#endif